### ISSUE TITLE
Karma startup failed

### ISSUE THREAD

**Issue by OrdonTeam** [Kotlin/kotlin-frontend-plugin#3]
Hi,
I've tried to run example frontend only on travis.
However I got karma startup error.
I randomly got similar error on my mac too.
I have no idea what can be cause of such behavior.
Thanks in advance
Karol

```java
:karma-start
karma: not actually running so has been killed
webpack: wait until bundle finished: 
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':karma-start'.
> karma startup failed
```

https://travis-ci.org/elpassion/todo-kotlin-react-example/builds/219248535

**Comment by cy6erGn0m** [comment]
Could you please check `build/logs/karma.log` for errors ?

**Comment by OrdonTeam** [comment]
Single line is there:
`webpack: wait until bundle finished:`
line 243 in https://travis-ci.org/elpassion/todo-kotlin-react-example/builds/221295191

**Comment by cy6erGn0m** [comment]
I see, the reason is that bundling takes too long so it kills karma. So actions to be done are:
- increase timeout
- make timeout configurable
- better diagnostics

**Comment by cy6erGn0m** [comment]
Should be fixed in 0.0.18. @OrdonTeam Could you please verify ?

**Comment by OrdonTeam** [comment]
I will, thanks

**Comment by Anmol92verma** [comment]
It works in 0.0.18, thanks !

**Comment by OrdonTeam** [comment]
Hm. It still doesn't work on travis.
Same error in the same line:
https://travis-ci.org/elpassion/todo-kotlin-react-example/builds/225899869.

@Anmol92verma Have you tried on travis? Is it open repository? Can we see your setup in travis yml?

**Comment by cy6erGn0m** [comment]
@OrdonTeam is it failed in 13 seconds? default timeout is 30 seconds. Are you sure you have upgraded?

**Comment by cy6erGn0m** [comment]
@OrdonTeam could you please try to specify in `gradle.properties` the following

```
org.kotlin.frontend.startup.timeout=120
```

**Comment by Pozo** [comment]
I could reproduce this as well.
Ubuntu 16.04LTS
java -version "1.8.0_101"
node --version v4.2.6

When I executed `./gradlew clean run  --debug` within `kotlin-frontend-plugin/examples/frontend-only` I've got this ( I copied only the :karma-start related lines ):

> 11:48:50.255 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':karma-start'.
> 11:48:50.259 [DEBUG] [org.gradle.api.Task] Running /usr/bin/node /home/zpolgar/workspace/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/bin/karma start
> 11:48:56.992 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
> 11:48:56.992 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 11:48:56.992 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
> 11:48:56.993 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 11:48:56.993 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 11:48:56.993 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
> 11:48:56.993 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 11:48:57.770 [ERROR] [org.gradle.api.Task] karma: not actually running so has been killed
> 11:48:57.770 [ERROR] [system.err] webpack: wait until bundle finished: 
> 11:48:58.823 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
> 11:48:58.823 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':karma-start'
> 11:48:58.823 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :karma-start FAILED

When I'm inspecting the running processes with Htop I can see a running karma but after this line `karma: not actually running so has been killed` It's disappear.

On the other hand, when I'm running `/usr/bin/node /home/zpolgar/workspace/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/bin/karma start` first in a separated terminal window, then `./gradlew clean run` It's working. 

In this case the  :karma-start task related lines are the following.

> 1111:51:51.467 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':karma-start'.
> 11:51:51.469 [DEBUG] [org.gradle.api.Task] Running /usr/bin/node /home/zpolgar/workspace/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/bin/karma start
> 11:51:51.471 [LIFECYCLE] [org.gradle.api.Task] karma started, open http://localhost:9876/ in your browser to run tests and see report
> 11:51:51.471 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
> 11:51:51.471 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':karma-start'
> 11:51:51.471 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :karma-start (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.005 secs.
> 11:51:51.471 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.20 completed (0 in use)
> 11:51:51.472 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.21 started (1 in use).
> 11:51:51.472 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :webpack-run (Thread[Daemon worker Thread 2,5,main]) started.
> 11:51:51.472 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :webpack-run
> 11:51:51.473 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':webpack-run'
> 11:51:51.473 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':webpack-run' into context took 0.0 secs.
> 

Hope this help in a way.

**Comment by cy6erGn0m** [comment]
@Pozo have you tried with 0.0.18 and `org.kotlin.frontend.startup.timeout=120` ? from you logs I can see it is 0.0.17

**Comment by Pozo** [comment]
Yes, I've started with your suggestion first.

All in all I tried a fresh clone with `org.kotlin.frontend.startup.timeout=120` and I tried tried with 0.0.18 (6d6f4fe) as well with `org.kotlin.frontend.startup.timeout=120` ( I've tried much bigger number as well ) but it does not work.

**Comment by cy6erGn0m** [comment]
Does it actually wait for so long but fails?

**Comment by Pozo** [comment]
Well I must admit I was a dumbass. I just misunderstood what did you mean by version 0.0.18. I thought that I must check out the newest version of the repository but I just had to bump the plugin version in `kotlin-frontend-plugin/examples/frontend-only/build.gradle`

Now it works like a charm.

Thank you for your help!

**Comment by OrdonTeam** [comment]
Setting timeout fixed this issue.
